language: java
addons:
  firefox: '49.0'
jdk:
- oraclejdk8
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
before_install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.15.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
- sudo apt-get install jq
- wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest
  | jq -r .assets[0].browser_download_url)
after_success:
- java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter
  -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
deploy:
  provider: heroku
  api_key:
    secure: V0XxUkMpV+pT8+XTvPHQdKAuKsH11IXGqov/ZbhammINYMM6JrtPX3Wo+B00N/2B6+buxvfYFGHMjcA5SM4yfpCGxifR1L3OPQ1DNIbkdSVX3KJnsmGuqQdeoUQJxmjkaCaIDO7eEt36apC3QoZU8gERtCkuCm9ydr08VujzuuOFIhJdUdydvcTmebGRZG3yCM72KNXZeWZROwcxqzlOIzPADwJ0aX2Z6Pz0rdR9sAgWSsiX8SVBTy2xU9C9zu/zjlPmhALPgcBW+39n/W+0jA5oWrMYpWdMgTqI8b5R020rkBn0wAodm1x/2iXH2xSBsVn3O9+p0u1i+M/Ctf/iZT5YMRw/Cpi2DJaq9PocUsMBe6IC94ABOlhGd2Nowhop8gEBoqOStCl9JENJ26qceY3MNIq1eTZvwsqBcqxYhVX0w5Z8y+kWOCyrum2gtiq/9nc7tzXygiMLwwSWjtsb/q+WlRAU7/TAMc3rz3B/KU+CJw2vWMi2CgeooQfK9Q9pkVpx9s01v+EOP7bxl6wuvgw9yYkM8zkjWr2mWGJTc637Osr5Kck+PIrK702Rp7snJFGtrNY2UAJv0zJDS4uqJT1QpKcHK7EmxDm9ZkZDEeesIH2UlGKQLhn9yHWFb3+Y6wKakT8Qu/LafVi17jvxq9UjkJoeXmIz5eGStRWTXeY=
  app: fast-sands-82937
  on:
    repo: betallica/lukuvinkkikirjasto
env:
  global:
    secure: XmufpgXbqT1MSYKmDNXRreHoh9JFgBHoDskcsVZIYuA9hWESvYbOg4RfOkhOzQwC2jxvDsUeaokPYZTBy/6LoYVM34oOfjYDi/jFBZfJpGCZJRCGNrhXDq0V1VygcOWE0KLSKktwGN4fGd/mPoTxWO0izLps8PsjnxKT2+aGrMQFgStH6cqdOaiIStHplpslv4fg+Ya1OcX1XQCHXxLtikYH15c5dqiR8K2N0ryJ/tU4W7Y2rp34o32x0E0AuuuFqnShRVC5EsyEphSIbFK/LVp96X1gQnidq0UlOXPGQQRfB/AGV7XanXROsyBdKVOQwgJUMYioIPBvOGqZnOKCLLth52l+gyJe1pUiFXDwEWytGJcjwIRq92NzyM8EyR1S+j65S3U+21DVcp4F/zcHI588SieO1B6dLDk1aqyW+QdXNM4ZafbjZwW7x0fx7vVPhN5MKhwAMbRebpqbL3zpNfgM5UpcMDV3BywfJTedwVIZbUV2minf02WKCgX8+Thts1m/9i4tm3IlVQR5wEQnIQitro0VY8w8YYWszoBTvWsWzqtBNZAK3mbma4vQhWQZtpFyqKAB7Dp09MnnWTMIeGdyP57+cRIS1sM67MfQTgVAvRW0z/0PFkas5x3Mc8EKfIsYbc+A2fBUCxWUMY2EEUN//n5yvzvkaPUtBxHlbRo=
