language: java
addons:
  firefox: '49.0'
jdk:
- oraclejdk8
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
before_install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.15.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
deploy:
  api_key:
    secure: KwPlDwxObS+A4+TPnLKu5V177EFNkbLc7XAZ11k3MwR4RTMGrl1oRUgh/BdSURcn/YLRiFJA577c2TEwtaHtfLNN2wG4gNt/ld/toUYnlqTLYcxjfhNZyzVYO3imF4vc4+AQMonfN5gC2FifZmQ0xeef8dkUqpTHDzqnW9ajGyzfXvxwkvtYYtmCmWRTfOWDSx1h8QpD2J21XbWy9HbWjF/lGzFWywktMlAZzs8XFyqgw9gQGJAYntoBgdsugGlG3+5OV37502OVdgsLHtyDWJuwYl2QcSohRRoPHwXLVxRKSqJECPCSIL/O081ZO4nFJf8I3l2sreUWBJ+/uUmNefMs8lVo6ZYYvDRA498Jn8UmundzZZXBQf1pvUrFmqTQtphG3a165sxWGzdDMbC1lJtiSzjMuth3nJHr2Khzzsyw1vBYcno1iuvvGWiOBZHafWcSeA8PaK85VvPHSs0XzwEt83r5JbLZ+AfeUxc8EWkP7oh2JZusv5C+ZNK6Rm4Xl6hj/phWSVKG90TVZvWyxFIo04uQWxeBguoTboiWvgDNEdYmkXbC4omrxLWD5BW30l8lm5gyhzUZp1wT4ZwHmVNjX6fl6Y202x8N0ZBas5sftGxbA7e8ydIQcNQ4vYmSWpK1LwjfHJzMld7lNh62Kzx3PV1oQhE6+PgPxzdjhn0=
